# easy_admin:
    # entities:
    #     # change the following to the namespaces of your own entities
    #     - AppBundle\Entity\Product
    #     - AppBundle\Entity\Category
    #     - AppBundle\Entity\User