# This file sets the configuration of the main menu. If your backend is simple,
# you probably can leave the 'menu' option empty and rely on the default menu
# created by EasyAdmin.
#
# NOTE: this demo application splits the backend configuration into several
# small files for educational purposes. In your application you can put the
# entire backend configuration in just one file.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at https://github.com/javiereguiluz/EasyAdminBundle
easy_admin:
    design:
        menu:
            - label: 'menu.product'
              icon: 'cake'
              children:
                  - { entity: 'Product', icon: 'view_list', label: 'menu.product.list', default: true, params: { sortField: 'created_at' } }
                  - { entity: 'Category', icon: 'style', label: 'menu.category' }
                  - { entity: 'Product', icon: 'add_circle', label: 'menu.product.add', params: { action: 'new' } }
            - { label: 'menu.customer', entity: 'User', icon: 'people' }
            - { label: 'menu.purchase', entity: 'Purchase', icon: 'credit_card', params: { sortField: 'delivery_date' } }
            - { label: 'menu.admin', entity: 'Admin', icon: 'people' }
            #- { label: 'menu.about' }
            # - { label: 'menu.about.home', url: 'https://github.com/javiereguiluz/EasyAdminBundle', icon: 'home', target: '_blank' }
            # - { label: 'menu.about.docs', url: 'https://github.com/javiereguiluz/EasyAdminBundle#getting-started-guide', icon: 'book', target: '_blank' }
            # - { label: 'menu.about.issues', url: 'https://github.com/javiereguiluz/EasyAdminBundle/issues', icon: 'github', target: '_blank' }
